### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by 0liUms** [davidhampgonsalves/Contact-Identicons#1]
On Samsung Galaxy S2 running Android Kit Kat 4.4 with Cyanogenmod 11 on DorimanX kernel.
I got the loading and the preview but after, nothing. ( I haven't reboot, I hope that's no required ? )

**Comment by rubo77** [comment]
It worked for me, a few years ago, but today tried on a Samsung galaxy a6 als it did not apply the new images to the contacts.

Simp


It starts and counts din, then it does show the option to "apply contact identicons" again
